import type {
  Document,
  Filter,
  FindOptions,
  OptionalUnlessRequiredId,
  UpdateFilter,
  UpdateOptions,
  InsertOneOptions,
  BulkWriteOptions,
  CountDocumentsOptions,
  AggregateOptions,
  FindOneAndUpdateOptions,
} from "mongodb";
import { getDb } from "./connect";
import type { CollectionName } from "./collections";

/**
 * TENANT ISOLATION — the single most important guard in the app.
 *
 * MongoDB has no row-level security, so isolation MUST be enforced here in the
 * application layer. `forTenant(tenantId)` returns a thin wrapper whose every
 * method AUTO-INJECTS `{ tenantId }` into:
 *   - every filter (find / findOne / update / delete / count / aggregate)
 *   - every inserted document (insertOne / insertMany)
 *
 * Route handlers and server actions MUST use ONLY this layer — never the raw
 * `getDb()` collection directly (the sole exception is super-admin-only code
 * that operates across tenants, e.g. listing/creating tenants).
 *
 * Even if a caller passes `{ tenantId: someOtherId }` in a filter or document,
 * we OVERWRITE it with the bound tenantId. There is no way to read or write
 * another tenant's data through this wrapper.
 */

// Anything stamped with the bound tenant. `_id` is generated by Mongo on insert.
type WithTenant = { tenantId: string };

function injectFilter<T extends Document>(
  tenantId: string,
  filter: Filter<T> = {} as Filter<T>
): Filter<T> {
  // Spread the caller's filter first, then force tenantId last so it cannot be
  // overridden or widened (e.g. via `$or`, `tenantId: { $ne }`, etc.).
  return { ...filter, tenantId } as Filter<T>;
}

function injectDoc<T extends Document>(
  tenantId: string,
  doc: OptionalUnlessRequiredId<T>
): OptionalUnlessRequiredId<T> {
  return { ...doc, tenantId } as OptionalUnlessRequiredId<T>;
}

export function forTenant(tenantId: string) {
  if (!tenantId || typeof tenantId !== "string") {
    throw new Error("forTenant(tenantId): a non-empty tenantId is required");
  }

  function collection<T extends Document = Document>(name: CollectionName) {
    const col = async () => (await getDb()).collection<T>(name);

    return {
      async find(filter: Filter<T> = {} as Filter<T>, options?: FindOptions) {
        return (await col()).find(injectFilter(tenantId, filter), options);
      },

      /** Convenience: scoped find materialised to an array. */
      async findArray(filter: Filter<T> = {} as Filter<T>, options?: FindOptions) {
        return (await col()).find(injectFilter(tenantId, filter), options).toArray();
      },

      async findOne(filter: Filter<T> = {} as Filter<T>, options?: FindOptions) {
        return (await col()).findOne(injectFilter(tenantId, filter), options);
      },

      async insertOne(doc: OptionalUnlessRequiredId<T>, options?: InsertOneOptions) {
        return (await col()).insertOne(injectDoc(tenantId, doc), options);
      },

      async insertMany(docs: OptionalUnlessRequiredId<T>[], options?: BulkWriteOptions) {
        return (await col()).insertMany(
          docs.map((d) => injectDoc(tenantId, d)),
          options
        );
      },

      async updateOne(
        filter: Filter<T>,
        update: UpdateFilter<T> | Partial<T>,
        options?: UpdateOptions
      ) {
        // On upsert, force tenantId onto the inserted doc via $setOnInsert so an
        // upserted document is never created without a tenantId.
        const merged = withTenantOnInsert(tenantId, update);
        return (await col()).updateOne(injectFilter(tenantId, filter), merged, options);
      },

      async updateMany(
        filter: Filter<T>,
        update: UpdateFilter<T> | Partial<T>,
        options?: UpdateOptions
      ) {
        const merged = withTenantOnInsert(tenantId, update);
        return (await col()).updateMany(injectFilter(tenantId, filter), merged, options);
      },

      async findOneAndUpdate(
        filter: Filter<T>,
        update: UpdateFilter<T> | Partial<T>,
        options?: FindOneAndUpdateOptions
      ) {
        const merged = withTenantOnInsert(tenantId, update);
        return (await col()).findOneAndUpdate(
          injectFilter(tenantId, filter),
          merged as UpdateFilter<T>,
          options ?? {}
        );
      },

      async deleteOne(filter: Filter<T>) {
        return (await col()).deleteOne(injectFilter(tenantId, filter));
      },

      async deleteMany(filter: Filter<T> = {} as Filter<T>) {
        return (await col()).deleteMany(injectFilter(tenantId, filter));
      },

      async countDocuments(filter: Filter<T> = {} as Filter<T>, options?: CountDocumentsOptions) {
        return (await col()).countDocuments(injectFilter(tenantId, filter), options);
      },

      async distinct(key: string, filter: Filter<T> = {} as Filter<T>) {
        return (await col()).distinct(key as never, injectFilter(tenantId, filter));
      },

      /**
       * Scoped aggregation: a `{ $match: { tenantId } }` stage is prepended so
       * the pipeline can only ever see this tenant's documents.
       */
      async aggregate<R extends Document = Document>(
        pipeline: Document[] = [],
        options?: AggregateOptions
      ) {
        return (await col()).aggregate<R>(
          [{ $match: { tenantId } }, ...pipeline],
          options
        );
      },
    };
  }

  return { tenantId, collection };
}

/**
 * Ensure that any `$setOnInsert`/`$set` upsert carries the tenantId, and that a
 * replacement-style update object also gets tenantId. We never trust the
 * caller's tenantId.
 */
function withTenantOnInsert<T extends Document>(
  tenantId: string,
  update: UpdateFilter<T> | Partial<T>
): UpdateFilter<T> {
  const u = update as Record<string, unknown>;
  const hasOperators = Object.keys(u).some((k) => k.startsWith("$"));

  if (hasOperators) {
    const setOnInsert = {
      ...(u.$setOnInsert as Record<string, unknown> | undefined),
      tenantId,
    };
    // Strip tenantId out of any $set the caller provided so it can't be changed.
    const set = u.$set ? { ...(u.$set as Record<string, unknown>) } : undefined;
    if (set) delete (set as Record<string, unknown>).tenantId;
    return {
      ...u,
      ...(set ? { $set: set } : {}),
      $setOnInsert: setOnInsert,
    } as unknown as UpdateFilter<T>;
  }

  // Replacement-style update object: force tenantId.
  return { ...(u as object), tenantId } as unknown as UpdateFilter<T>;
}

export type ScopedDb = ReturnType<typeof forTenant>;
export type { WithTenant };
